modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-BoneTorch/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-bone-torch"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="bonetorch" #mandatory
version="0.0.1" #mandatory
displayName="[SBM] BoneTorch" #mandatory
description='''Simple mod to create torches from bones''' #mandatory

[[dependencies.bonetorch]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bonetorch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"